"use client"
import { useEffect, useState } from 'react'
import PaymentSettings from './payment-settings'
import AdSettings from './ad-settings'

type Product={id:number;name:string;slug:string;description:string;price:number;product_type:string;delivery_url?:string|null;storage_path?:string|null;image_url?:string|null;active:boolean;featured:boolean}
type Order={id:string;total:number;payment_method:string;sender_number:string;transaction_id:string;status:string;created_at:string;order_items:{product_name:string;unit_price:number;quantity:number}[]}
type Category={id:number;name:string}

export default function Admin(){
 const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [tab,setTab]=useState('products');const [msg,setMsg]=useState('');const [form,setForm]=useState({name:'',slug:'',description:'',price:'',productType:'link',deliveryUrl:'',storagePath:'',imageUrl:'',categoryId:''})
 async function load(){const [p,o,c]=await Promise.all([fetch('/api/store/admin/products'),fetch('/api/store/admin/orders'),fetch('/api/store/categories')]);if(p.ok)setProducts((await p.json()).products||[]);if(o.ok)setOrders((await o.json()).orders||[]);if(c.ok)setCategories((await c.json()).categories||[])}
 useEffect(()=>{load()},[])
 async function addProduct(e:React.FormEvent){e.preventDefault();setMsg('');const r=await fetch('/api/store/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:Number(form.price),categoryId:form.categoryId?Number(form.categoryId):null,image_url:form.imageUrl||null})});const d=await r.json();if(!r.ok)setMsg(d.error||'Could not create product');else{setMsg('Product created.');setForm({name:'',slug:'',description:'',price:'',productType:'link',deliveryUrl:'',storagePath:'',imageUrl:'',categoryId:''});load()}}
 async function updateProduct(id:number,patch:Partial<Product>){const r=await fetch('/api/store/admin/products',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch})});if(!r.ok){const d=await r.json();setMsg(d.error||'Update failed')}else load()}
 async function updateOrder(id:string,status:string){const r=await fetch('/api/store/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json();setMsg(r.ok?`Order marked ${status}.`:d.error||'Update failed');load()}
 return <main className="admin-page"><div className="admin-wrap"><div className="admin-hero"><div><span className="eyebrow">CONTROL CENTER</span><h1>Run the <em>store.</em></h1><p>Products, payment settings, verification, digital delivery and ad code in one protected workspace.</p></div><div className="admin-status"><b>LIVE CONTROL</b><span>Protected by admin access</span></div></div>
 <div className="admin-tabs">{[['products','Products'],['orders','Orders'],['payments','Payments'],['ads','Ads'],['delivery','Delivery']].map(t=><button className={tab===t[0]?'active':''} onClick={()=>setTab(t[0])} key={t[0]}>{t[1]}</button>)}</div>{msg&&<div className="admin-message">{msg}</div>}
 {tab==='products'&&<div className="admin-grid"><section className="admin-panel"><div className="panel-title"><span className="eyebrow">CATALOG</span><h2>Add product</h2></div><form className="admin-form" onSubmit={addProduct}><input placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Slug (optional)" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><textarea placeholder="Short product description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="admin-two"><input type="number" min="0" step="0.01" placeholder="Price in BDT" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><select value={form.productType} onChange={e=>setForm({...form,productType:e.target.value})}><option value="link">Website / access link</option><option value="download">Download file</option><option value="license">License / key</option></select><input placeholder="Product image URL" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/><input placeholder="Delivery URL / access website" value={form.deliveryUrl} onChange={e=>setForm({...form,deliveryUrl:e.target.value})}/><input placeholder="Private storage path for downloads" value={form.storagePath} onChange={e=>setForm({...form,storagePath:e.target.value})}/><button className="admin-primary">Publish product</button></form></section><section className="admin-panel"><div className="panel-title"><span className="eyebrow">ACTIVE CATALOG</span><h2>{products.length} products</h2></div><div className="admin-list">{products.map(p=><div className="admin-product" key={p.id}>{p.image_url?<img src={p.image_url} alt=""/>:<div className="admin-thumb">{p.name.slice(0,1)}</div>}<div><b>{p.name}</b><span>৳{Number(p.price).toLocaleString()} · {p.product_type}</span><small>{p.delivery_url||p.storage_path?'Delivery configured':'Delivery not configured'}</small></div><button onClick={()=>updateProduct(p.id,{active:!p.active})}>{p.active?'Pause':'Activate'}</button></div>)}</div></section></div>}
 {tab==='orders'&&<section className="admin-panel full-panel"><div className="panel-title"><span className="eyebrow">PAYMENT VERIFICATION</span><h2>Orders awaiting review</h2></div><div className="order-list">{orders.map(o=><div className="admin-order" key={o.id}><div><b>#{o.id.slice(0,8)}</b><span>{new Date(o.created_at).toLocaleString()}</span><p>{o.order_items?.map(i=>i.product_name).join(' · ')}</p></div><div><strong>৳{Number(o.total).toLocaleString()}</strong><span>{o.payment_method} · {o.sender_number}</span><span>TX: {o.transaction_id}</span></div><div className={`status ${o.status}`}>{o.status}</div><div className="order-actions"><button onClick={()=>updateOrder(o.id,'paid')}>Approve</button><button onClick={()=>updateOrder(o.id,'rejected')}>Reject</button></div></div>)}{!orders.length&&<div className="admin-empty">No orders yet.</div>}</div></section>}
 {tab==='payments'&&<section className="admin-panel full-panel"><div className="panel-title"><span className="eyebrow">LOCAL PAYMENT</span><h2>bKash · Nagad · Rocket</h2><p>Set the receiver number and customer-facing instructions. Keep credentials out of the storefront.</p></div><PaymentSettings/></section>}
 {tab==='ads'&&<section className="admin-panel full-panel"><div className="panel-title"><span className="eyebrow">AD CONTROL</span><h2>Ad code & placements</h2><p>Paste provider-supplied ad code into a slot, turn it on or off, and save. No ad code is hard-coded into the public pages.</p></div><AdSettings/></section>}
 {tab==='delivery'&&<section className="admin-panel full-panel"><div className="panel-title"><span className="eyebrow">DIGITAL DELIVERY</span><h2>What the customer receives</h2></div><div className="delivery-guide"><div><b>Download</b><p>Upload the file to the private digital-products bucket and set its storage path. Paid customers receive a short-lived signed link.</p></div><div><b>Website / access link</b><p>Put the customer-facing website or app URL in the delivery URL field. It becomes visible in the customer account only after approval.</p></div><div><b>License / key</b><p>Use a controlled delivery URL or license workflow; do not place secrets in public product descriptions.</p></div></div></section>}
 </div></main>
}
