"use client"

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Order={id:string;total:number;status:string;payment_method:string;created_at:string;order_items:{id:number;product_name:string;unit_price:number;quantity:number}[]}

export default function Account() {
  const supabase = createClient()
  const [mode, setMode] = useState<'login' | 'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [userEmail,setUserEmail]=useState<string|null>(null); const [orders,setOrders]=useState<Order[]>([])
  async function loadUser(){const {data}=await supabase.auth.getUser();setUserEmail(data.user?.email||null);if(data.user){const r=await fetch('/api/store/orders');if(r.ok){const d=await r.json();setOrders(d.orders||[])}}}
  useEffect(()=>{loadUser()},[])
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)setMessage(error.message);else if(!data.session)setMessage('Account created. Check your email if confirmation is enabled, then sign in.');else window.location.href='/account'}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else window.location.href='/account'}setLoading(false)}
  async function signOut(){await supabase.auth.signOut();setUserEmail(null);setOrders([]);setMessage('Signed out successfully.')}
  if(userEmail)return <main className="authpage"><div className="authcard account-dashboard"><Link className="brand" href="/">DigiPlyra</Link><span className="eyebrow">CUSTOMER ACCOUNT</span><h1>Your <em>library.</em></h1><p>Signed in as <b>{userEmail}</b>. Approved digital products and access links are shown on each paid order.</p><div className="account-actions"><Link className="copy" href="/">Continue shopping</Link><Link className="copy" href="/cart">Open cart</Link></div><div className="account-orders"><div className="account-section-title"><b>Order history</b><span>{orders.length} orders</span></div>{orders.map(o=><div className="account-order" key={o.id}><div><b>#{o.id.slice(0,8)}</b><span>{new Date(o.created_at).toLocaleDateString()} · {o.payment_method}</span>{o.order_items.map(i=><p key={i.id}>{i.product_name} · ৳{Number(i.unit_price).toLocaleString()}</p>)}</div><div className={`status ${o.status}`}>{o.status}</div>{o.status==='paid'&&<Link className="access-link" href={`/account/orders?order=${o.id}`}>Open delivery →</Link>}</div>)}{!orders.length&&<div className="authmessage">No orders yet. Add a product to your cart and complete checkout.</div>}</div><div className="authmessage"><b>Secure delivery</b><br/>Download files use protected access, while website/access links are revealed only for approved orders.</div><button className="secondary-button" onClick={signOut}>Sign out</button>{message&&<div className="authmessage">{message}</div>}</div></main>
  return <main className="authpage"><div className="authcard"><Link className="brand" href="/">DigiPlyra</Link><span className="eyebrow">CUSTOMER ACCOUNT</span><h1>{mode==='login'?<>Welcome <em>back.</em></>:<>Create <em>account.</em></>}</h1><p>{mode==='login'?'Sign in to view your orders and approved digital deliveries.':'Create an account so your paid downloads and access links stay in one place.'}</p><form onSubmit={submit} className="authform">{mode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" autoComplete="email" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={6} required/><button disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form>{message&&<div className="authmessage">{message}</div>}<button className="text-button" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button><Link href="/">← Back to store</Link></div></main>
}
