"use client";

import { useEffect, useMemo, useState } from "react";
import PromptVisual from "@/components/PromptVisual";

type Prompt={id?:number;slug:string;title:string;excerpt:string;prompt_text?:string;prompt_type:string;model?:string;tags?:string[];preview_image_url?:string|null;categories?:{name:string;slug:string}|{name:string;slug:string}[]|null;ai_models?:{name:string;slug:string}|{name:string;slug:string}[]|null};

const categories=[["✦","Image Prompts","Create visuals, portraits, products and cinematic scenes.","image"],["◉","Video Prompts","Build cinematic shots, ads, reels and image-to-video concepts.","video"],["⌘","Chat & Writing","Writing, research, productivity and everyday AI.","chat"],["</>","Coding","Debug, build, review and automate with AI.","coding"],["↗","Marketing","Ads, SEO, branding, social content and sales.","marketing"],["✺","Creative","Illustration, 3D, fashion, posters and experimental ideas.","creative"]];

export default function Home(){
 const [query,setQuery]=useState(""); const [type,setType]=useState(""); const [items,setItems]=useState<Prompt[]>([]); const [loading,setLoading]=useState(false); const [hasMore,setHasMore]=useState(true); const [cursor,setCursor]=useState<string|null>(null); const [copied,setCopied]=useState("");
 const filtered=useMemo(()=>items,[items]);

 useEffect(()=>{let cancelled=false; const load=async()=>{setLoading(true); try{const qs=new URLSearchParams(); if(query)qs.set("q",query); if(type)qs.set("type",type); qs.set("limit","24"); const r=await fetch("/api/prompts?"+qs.toString(),{cache:"no-store"}); if(r.ok){const j=await r.json(); if(!cancelled){setItems(Array.isArray(j.data)?j.data:[]);setCursor(j.nextCursor||null);setHasMore(Boolean(j.hasMore))}}}catch{} finally{if(!cancelled)setLoading(false)}}; const t=setTimeout(load,180); return()=>{cancelled=true;clearTimeout(t)}},[query,type]);

async function loadMore(){if(loading||!hasMore||!cursor)return; setLoading(true); try{const qs=new URLSearchParams({limit:"24",cursor}); if(query)qs.set("q",query); if(type)qs.set("type",type); const r=await fetch("/api/prompts?"+qs.toString(),{cache:"no-store"}); if(r.ok){const j=await r.json(); setItems(prev=>[...prev,...(Array.isArray(j.data)?j.data:[])]); setCursor(j.nextCursor||null); setHasMore(Boolean(j.hasMore));}}catch{}finally{setLoading(false)}}

useEffect(()=>{const el=document.getElementById("prompt-sentinel"); if(!el)return; const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)loadMore()},{rootMargin:"900px"}); observer.observe(el); return()=>observer.disconnect()},[cursor,hasMore,loading,query,type]);

 async function copyPrompt(title:string,prompt:string){try{await navigator.clipboard.writeText(prompt);setCopied(title);setTimeout(()=>setCopied(""),1400)}catch{}}

 return <main>
 <header className="nav"><a className="brand" href="/">PROMPT<span>EXA</span></a><nav className="navlinks"><a href="#discover">Discover</a><a href="#categories">Categories</a><a href="#ai-tools">AI Tools</a><a href="#collections">Collections</a></nav><div className="navactions"><button className="iconbtn" aria-label="Focus search" onClick={()=>document.getElementById("prompt-search")?.focus()}>⌕</button><a className="ghost" href="/auth">Sign in</a></div></header>
 <section className="hero"><div className="eyebrow">THE VISUAL AI PROMPT DISCOVERY PLATFORM</div><h1>Find the prompt.<br/><em>See the possibility.</em></h1><p>Explore a growing library of carefully structured AI prompts for images, videos, writing, coding, marketing and more.</p><div className="search"><span>⌕</span><input id="prompt-search" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search prompts" placeholder="Search 50,000+ AI prompts..." /><kbd>⌘ K</kbd></div><div className="quick"><span>Filter:</span>{["","image","video","coding","marketing"].map(v=><button key={v} onClick={()=>setType(v)} className={type===v?"active":""}>{v||"all"}</button>)}</div></section>
 <section className="section" id="discover"><div className="sectionhead"><div><span className="eyebrow">DISCOVER {loading?"· UPDATING":""}</span><h2>Prompts worth exploring</h2></div><a className="viewall" href="#categories">Explore categories →</a></div><div className="promptgrid">{filtered.map((p,i)=>{const model=Array.isArray(p.ai_models)?p.ai_models[0]?.name:p.ai_models?.name||p.model||"AI"; const slug=p.slug; return <article className="promptcard" key={slug}><a href={"/prompts/"+slug} className={"visual v"+(i%4)}><PromptVisual src={"/api/prompt-image?slug="+encodeURIComponent(slug)+"&title="+encodeURIComponent(p.title)+"&type="+encodeURIComponent(p.prompt_type)+"&model="+encodeURIComponent(model)+"&v=4"} alt={p.title} priority={i<4} /><span>{p.prompt_type.toUpperCase()}</span></a><div className="cardbody"><div className="meta"><span>{p.prompt_type}</span><span>•</span><span>{model}</span></div><h3><a href={"/prompts/"+slug}>{p.title}</a></h3><p>{p.excerpt}</p><div className="cardfoot"><button className="copy" onClick={()=>copyPrompt(p.title,p.prompt_text||p.excerpt)}>{copied===p.title?"Copied ✓":"Copy prompt"}</button><a className="save" href={"/prompts/"+slug} aria-label={"Open "+p.title}>↗</a></div></div></article>})}</div><div id="prompt-sentinel" aria-hidden="true" style={{height:1}} />{loading&&<div className="empty">Loading more prompts…</div>}{!loading&&filtered.length===0&&<div className="empty">No prompts match “{query}”. Try another search.</div>}{!hasMore&&filtered.length>0&&<div className="empty">You reached the end of this collection.</div>}</section>
 <section className="section muted" id="categories"><div className="sectionhead"><div><span className="eyebrow">EXPLORE</span><h2>Start with a category</h2></div></div><div className="catgrid">{categories.map(c=><a className="cat" key={c[1]} href={"/categories/"+c[3]}><div className="caticon">{c[0]}</div><h3>{c[1]}</h3><p>{c[2]}</p><span>Explore →</span></a>)}</div></section>
 <section className="aitools" id="ai-tools"><div className="sectionhead"><div><span className="eyebrow">AI TOOL DIRECTORY</span><h2>Choose the right AI for the job</h2></div><span className="aitools-note">Prompt recommendations by workflow</span></div><div className="aitoolgrid">{[["Promptexa AI","Own AI workspace for prompt building, optimization and format conversion.","All workflows","✦","/ai"],["ChatGPT","Chat, writing, research, reasoning and image creation/editing.","Chat · Writing · Image","◌","https://chatgpt.com"],["Gemini","Multimodal chat plus image generation and editing.","Chat · Image · Research","◇","https://gemini.google.com"],["Midjourney","Image generation, image editing and image-to-video workflows.","Image · Editing · Video","◈","https://www.midjourney.com"],["Adobe Firefly","Generative image and video creation with Adobe creative workflows.","Image · Video · Editing","▧","https://firefly.adobe.com"],["Leonardo AI","Image generation, editing, upscaling and video workflows.","Image · Editing · Video","✺","https://app.leonardo.ai"],["Runway","Video generation, image-to-video and prompt-based video editing.","Video · Editing","▶","https://app.runwayml.com"]].map(([name,desc,uses,icon,href])=><a className="aitool" href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} key={name}><div className="aitooltop"><span className="aitoolicon">{icon}</span><span className="aitoolarrow">↗</span></div><h3>{name}</h3><p>{desc}</p><small>{uses}</small></a>)}</div></section><section className="statement" id="models"><span className="eyebrow">BUILT FOR CREATION</span><h2>Discover → Understand → Copy → Create</h2><p>Every prompt is designed to show what it can create, how it works and where it fits into your workflow.</p></section>
 <footer id="collections"><div className="brand">PROMPT<span>EXA</span></div><p>Visual AI prompt discovery, built for creators.</p><div className="footerlinks"><a href="#discover">Discover</a><a href="#categories">Categories</a><a href="#ai-tools">AI Tools</a><a href="/auth">Account</a></div></footer>
 </main>
}