"use client"

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import AdSlot from '@/app/components/ad-slot'

type Product={id:number;name:string;price:number;image_url?:string|null;description:string}
type Method={id:number;name:string;code:string;instructions?:string|null;account_hint?:string|null;logo_url?:string|null}

export default function Checkout(){
 const supabase=createClient(); const [items,setItems]=useState<Product[]>([]); const [methods,setMethods]=useState<Method[]>([]); const [method,setMethod]=useState('bkash'); const [sender,setSender]=useState(''); const [txid,setTxid]=useState(''); const [note,setNote]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [email,setEmail]=useState<string|null>(null)
 useEffect(()=>{const ids=(()=>{try{return JSON.parse(localStorage.getItem('digiplyra-cart')||'[]')}catch{return []}})(); Promise.all([fetch('/api/store/products').then(r=>r.json()),fetch('/api/store/payments').then(r=>r.json()),supabase.auth.getUser()]).then(([p,m,u])=>{setItems((p.products||[]).filter((x:Product)=>ids.includes(x.id)));setMethods(m.methods||[]);setEmail(u.data.user?.email||null)}).catch(()=>{})},[])
 const total=useMemo(()=>items.reduce((s,p)=>s+Number(p.price),0),[items]); const selected=methods.find(m=>m.code===method)
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');if(!email){setMessage('Please sign in or create an account before checkout.');setLoading(false);return}if(!items.length){setMessage('Your cart is empty.');setLoading(false);return}const res=await fetch('/api/store/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:items.map(p=>p.id),paymentMethod:method,senderNumber:sender,transactionId:txid,paymentNote:note})});const data=await res.json();if(!res.ok)setMessage(data.error||'Could not create order.');else{localStorage.setItem('digiplyra-cart','[]');window.dispatchEvent(new Event('cart-updated'));setMessage(`Order ${data.order?.id?.slice(0,8)||''} submitted. Your payment is pending admin verification.`)}setLoading(false)}
 if(!items.length)return <main className="checkout-page"><div className="checkout-wrap"><AdSlot slot="checkout_top"/><div className="checkout-empty"><span className="eyebrow">CHECKOUT</span><h1>Your cart is <em>empty.</em></h1><p>Add a product first, then return here to choose bKash, Nagad or Rocket.</p><Link href="/" className="hero-primary">Browse products</Link></div></div></main>
 return <main className="checkout-page"><div className="checkout-wrap"><div className="checkout-top"><Link href="/cart">← Cart</Link><span>Secure digital checkout</span></div><AdSlot slot="checkout_top"/><div className="checkout-grid"><section className="checkout-form"><div><span className="eyebrow">PAYMENT & ORDER</span><h1>Finish your <em>order.</em></h1><p className="checkout-lead">{email?`Signed in as ${email}`:'Sign in to attach this order to your customer account.'}</p></div>{!email&&<div className="checkout-alert"><b>Account required</b><span>Create or sign in to an account so approved products can be delivered securely.</span><Link href="/account">Open account →</Link></div>}<div className="payment-methods"><label>Choose payment method</label><div className="method-grid">{methods.map(m=><button type="button" key={m.code} className={method===m.code?'method active':'method'} onClick={()=>setMethod(m.code)}>{m.logo_url?<img src={m.logo_url} alt=""/>:<span className={`method-mark ${m.code}`}>{m.name.slice(0,1)}</span>}<span>{m.name}</span><i>{method===m.code?'✓':''}</i></button>)}</div></div>{selected&&<div className="payment-instructions"><div><b>{selected.name} payment</b><span>{selected.account_hint||'Follow the payment instructions supplied by the store.'}</span></div><p>{selected.instructions||'Send the exact order amount, then enter your sender number and transaction ID below.'}</p></div>}<form onSubmit={submit} className="checkout-fields"><label>Sender number<input value={sender} onChange={e=>setSender(e.target.value)} placeholder="01XXXXXXXXX" inputMode="tel" required/></label><label>Transaction ID<input value={txid} onChange={e=>setTxid(e.target.value)} placeholder="Enter payment transaction ID" required/></label><label>Note <small>optional</small><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything the admin should know?"/></label><button className="checkout-btn" disabled={loading||!email}>{loading?'Submitting…':'Submit payment for verification'}</button></form>{message&&<div className="authmessage">{message}</div>}</section><aside className="checkout-summary"><span className="eyebrow">YOUR ORDER</span>{items.map((p,i)=><div className="summary-product" key={`${p.id}-${i}`}>{p.image_url?<img src={p.image_url} alt=""/>:<div>{p.name.slice(0,1)}</div>}<span>{p.name}<small>Digital product</small></span><b>৳{Number(p.price).toLocaleString()}</b></div>)}<hr/><div className="summary-total"><span>Total</span><strong>৳{total.toLocaleString()}</strong></div><div className="summary-safe">🔒 Payment reference is stored with the order. Digital delivery is unlocked only after approval.</div></aside></div></div></main>
}
