create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role text not null default 'customer' check (role in ('customer','admin')), created_at timestamptz not null default now());
create table if not exists public.store_categories (id bigint generated always as identity primary key, name text not null, slug text not null unique, description text not null default '', active boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now());
create table if not exists public.products (id bigint generated always as identity primary key, category_id bigint references public.store_categories(id) on delete set null, name text not null, slug text not null unique, description text not null default '', price numeric(12,2) not null check (price >= 0), product_type text not null default 'download' check (product_type in ('download','link','license')), delivery_url text, storage_path text, active boolean not null default true, featured boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.payment_methods (id bigint generated always as identity primary key, name text not null, code text not null unique, instructions text not null default '', account_hint text, active boolean not null default true, sort_order int not null default 0);
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, total numeric(12,2) not null check (total >= 0), payment_method text not null, sender_number text, transaction_id text, status text not null default 'pending' check (status in ('pending','paid','rejected','cancelled')), payment_note text, paid_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_items (id bigint generated always as identity primary key, order_id uuid not null references public.orders(id) on delete cascade, product_id bigint not null references public.products(id) on delete restrict, product_name text not null, unit_price numeric(12,2) not null check (unit_price >= 0), quantity int not null default 1 check (quantity > 0));
create table if not exists public.ad_slots (id bigint generated always as identity primary key, slot_key text not null unique, title text not null default '', code text not null default '', enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.store_settings (key text primary key, value text not null default '', updated_at timestamptz not null default now());

create or replace function public.handle_new_profile() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_profile();
create or replace function public.is_admin() returns boolean language sql security definer set search_path = public stable as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;

alter table public.profiles enable row level security; alter table public.store_categories enable row level security; alter table public.products enable row level security; alter table public.payment_methods enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.ad_slots enable row level security; alter table public.store_settings enable row level security;
create policy profiles_self on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy categories_public_read on public.store_categories for select to anon,authenticated using(active=true or public.is_admin()); create policy categories_admin_write on public.store_categories for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy products_public_read on public.products for select to anon,authenticated using(active=true or public.is_admin()); create policy products_admin_write on public.products for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy payment_public_read on public.payment_methods for select to anon,authenticated using(active=true or public.is_admin()); create policy payment_admin_write on public.payment_methods for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy orders_self on public.orders for select to authenticated using(user_id=auth.uid() or public.is_admin()); create policy orders_insert_self on public.orders for insert to authenticated with check(user_id=auth.uid()); create policy orders_admin_update on public.orders for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy order_items_self on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin()))); create policy order_items_insert_self on public.order_items for insert to authenticated with check(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid())); create policy order_items_admin_write on public.order_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy ads_public_read on public.ad_slots for select to anon,authenticated using(enabled=true or public.is_admin()); create policy ads_admin_write on public.ad_slots for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy settings_public_read on public.store_settings for select to anon,authenticated using(key in('site_name','site_description','support_email') or public.is_admin()); create policy settings_admin_write on public.store_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());

insert into public.store_categories(name,slug,description,sort_order) values ('Subscriptions','subscriptions','Legal digital subscriptions and memberships.',1),('Apps & Software','apps-software','Legal apps, software and digital tools.',2),('Templates','templates','Digital templates and creator resources.',3),('Files & Downloads','files-downloads','Downloadable digital products.',4) on conflict(slug) do nothing;
insert into public.payment_methods(name,code,instructions,sort_order) values ('bKash','bkash','Use the payment instructions shown at checkout, then submit your transaction ID.',1),('Nagad','nagad','Use the payment instructions shown at checkout, then submit your transaction ID.',2),('Rocket','rocket','Use the payment instructions shown at checkout, then submit your transaction ID.',3) on conflict(code) do nothing;
insert into public.ad_slots(slot_key,title,enabled) values ('home_top','Homepage top ad',false),('home_middle','Homepage middle ad',false),('product_bottom','Product page bottom ad',false) on conflict(slot_key) do nothing;
insert into public.store_settings(key,value) values ('site_name','DigiPlyra'),('site_description','Legal digital products and services.'),('support_email','') on conflict(key) do nothing;

insert into storage.buckets(id,name,public) values('digital-products','digital-products',false) on conflict(id) do update set public=false;
create policy digital_products_admin_insert on storage.objects for insert to authenticated with check(bucket_id='digital-products' and public.is_admin());
create policy digital_products_admin_update on storage.objects for update to authenticated using(bucket_id='digital-products' and public.is_admin()) with check(bucket_id='digital-products' and public.is_admin());
create policy digital_products_admin_delete on storage.objects for delete to authenticated using(bucket_id='digital-products' and public.is_admin());
create policy digital_products_customer_read on storage.objects for select to authenticated using(bucket_id='digital-products' and (public.is_admin() or exists(select 1 from public.products p join public.order_items oi on oi.product_id=p.id join public.orders o on o.id=oi.order_id where o.user_id=auth.uid() and o.status='paid' and p.storage_path=name)));

revoke execute on function public.handle_new_profile() from anon, authenticated;
revoke execute on function public.is_admin() from anon, authenticated;
